version: "3.9"
services:
  app:
    container_name: clean-node-api
    image: node:14
    working_dir: /app/clean-node-api
    restart: always
    command: bash -c "npm install --production && npm run debug"
    depends_on:
      - mongo
    ports:
      - 13000:3000
      - 9222:9222
    volumes:
      - ./dist/:/app/clean-node-api/dist/
      - ./package.json:/app/clean-node-api/package.json
      - ./package-lock.json:/app/clean-node-api/package-lock.json
    links:
      - mongo
  mongo:
    container_name: mongo-clean-node-api
    image: mongo:4
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongo:/data/db
      - mongo:/data/configdb
      - mongo:/var/lib/mongodb
volumes:
  mongo:
    driver: local
