version: "3.9"
services:
  app:
    container_name: clean-node-api
    image: node:16
    working_dir: /app/clean-node-api
    restart: always
    command: bash -c "npm install && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
      - PORT=5050
    depends_on:
      - mongo
    ports:
      - 5050:5050
      - 9229:9229
    volumes:
      - ./dist/:/app/clean-node-api/dist/
      - ./package.json:/app/clean-node-api/package.json
      - ./package-lock.json:/app/clean-node-api/package-lock.json
    links:
      - mongo
  mongo:
    container_name: mongo-clean-node-api
    image: mongo:4
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongo:/data/db
      - mongo:/data/configdb
      - mongo:/var/lib/mongodb
volumes:
  mongo:
    driver: local
